import os
import json
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

def generate_audit_report(business: dict, audit: dict) -> str:
    """
    Generates a professional HTML audit report for a business.
    Saves it to data/reports/ and returns the file path.
    """
    os.makedirs("data/reports", exist_ok=True)

    business_name = business.get("name", "Unknown Business")
    address = business.get("address", "")
    rating = business.get("rating", 0)
    review_count = business.get("review_count", 0)
    website = business.get("website", "Not listed")

    visibility_score = audit.get("visibility_score", 0)
    revenue_lost = audit.get("estimated_monthly_revenue_lost_usd", 0)
    searches_lost = audit.get("estimated_monthly_searches_lost", 0)
    critical_issues = audit.get("critical_issues", [])
    top_fixes = audit.get("top_3_fixes", [])
    summary = audit.get("audit_summary", "")

    # Score color
    if visibility_score >= 70:
        score_color = "#22c55e"
        score_label = "Fair"
    elif visibility_score >= 40:
        score_color = "#f97316"
        score_label = "Poor"
    else:
        score_color = "#ef4444"
        score_label = "Critical"

    # Build issues list
    issues_html = "".join([
        f'<li style="margin-bottom:8px; padding:8px; background:#fef2f2; border-left:3px solid #ef4444; border-radius:4px;">'
        f'⚠️ {issue}</li>'
        for issue in critical_issues
    ])

    # Build fixes list
    fixes_html = "".join([
        f'<li style="margin-bottom:8px; padding:8px; background:#f0fdf4; border-left:3px solid #22c55e; border-radius:4px;">'
        f'✅ {fix}</li>'
        for fix in top_fixes
    ])

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GBPilot Audit Report - {business_name}</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 0; padding: 0; background: #f8fafc; color: #1e293b; }}
  .container {{ max-width: 700px; margin: 0 auto; padding: 40px 20px; }}
  .header {{ background: linear-gradient(135deg, #1e40af, #3b82f6); color: white; padding: 30px; border-radius: 12px; margin-bottom: 24px; }}
  .header h1 {{ margin: 0 0 8px 0; font-size: 22px; }}
  .header p {{ margin: 0; opacity: 0.85; font-size: 14px; }}
  .score-card {{ display: flex; gap: 16px; margin-bottom: 24px; }}
  .metric {{ flex: 1; background: white; border-radius: 12px; padding: 20px; text-align: center; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }}
  .metric .value {{ font-size: 32px; font-weight: bold; }}
  .metric .label {{ font-size: 12px; color: #64748b; margin-top: 4px; }}
  .section {{ background: white; border-radius: 12px; padding: 24px; margin-bottom: 20px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); }}
  .section h2 {{ margin: 0 0 16px 0; font-size: 16px; color: #1e40af; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; }}
  ul {{ margin: 0; padding-left: 0; list-style: none; }}
  .summary {{ background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 16px; font-size: 14px; line-height: 1.6; color: #1e40af; }}
  .cta {{ background: linear-gradient(135deg, #1e40af, #3b82f6); color: white; padding: 24px; border-radius: 12px; text-align: center; margin-top: 24px; }}
  .cta h2 {{ margin: 0 0 8px 0; font-size: 18px; }}
  .cta p {{ margin: 0 0 16px 0; opacity: 0.9; font-size: 14px; }}
  .cta a {{ background: white; color: #1e40af; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 14px; }}
  .footer {{ text-align: center; color: #94a3b8; font-size: 12px; margin-top: 24px; }}
</style>
</head>
<body>
<div class="container">

  <div class="header">
    <h1>📊 Google Business Profile Audit</h1>
    <p>{business_name} · {address}</p>
    <p style="margin-top:8px; font-size:12px;">Generated by GBPilot AI · {datetime.now().strftime("%B %d, %Y")}</p>
  </div>

  <div class="score-card">
    <div class="metric">
      <div class="value" style="color:{score_color};">{visibility_score}/100</div>
      <div class="label">Visibility Score ({score_label})</div>
    </div>
    <div class="metric">
      <div class="value" style="color:#ef4444;">${revenue_lost:,}</div>
      <div class="label">Est. Monthly Revenue Lost</div>
    </div>
    <div class="metric">
      <div class="value" style="color:#f97316;">{searches_lost}</div>
      <div class="label">Monthly Searches Missed</div>
    </div>
    <div class="metric">
      <div class="value" style="color:#64748b;">⭐ {rating}</div>
      <div class="label">{review_count} Reviews</div>
    </div>
  </div>

  <div class="section">
    <h2>📌 Audit Summary</h2>
    <div class="summary">{summary}</div>
  </div>

  <div class="section">
    <h2>🚨 Critical Issues Found</h2>
    <ul>{issues_html}</ul>
  </div>

  <div class="section">
    <h2>🔧 Top 3 Fixes (We Handle These For You)</h2>
    <ul>{fixes_html}</ul>
  </div>

  <div class="cta">
    <h2>Ready to Fix This?</h2>
    <p>GBPilot's AI agents handle everything automatically — posts, fixes, monitoring — for just $79/month per location.</p>
    <a href="https://gbpilot.com/start">Start Your Free 7-Day Trial →</a>
  </div>

  <div class="footer">
    <p>GBPilot · AI-Powered Google Business Profile Management</p>
    <p>This report was generated automatically by GBPilot's Audit Agent.</p>
  </div>

</div>
</body>
</html>
"""

    # Save file
    safe_name = business_name.replace(" ", "_").replace("/", "_")[:40]
    filename = f"data/reports/{safe_name}_audit.html"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"  [REPORT] Saved to {filename}")
    return filename


if __name__ == "__main__":
    # Test with sample data
    test_business = {
        "name": "Jim Stephens Foreign Car Service",
        "address": "800 Plum St, Cincinnati, OH 45202, USA",
        "rating": 5.0,
        "review_count": 47,
        "website": "Not listed",
        "maps_url": "https://maps.google.com"
    }

    test_audit = {
        "business_name": "Jim Stephens Foreign Car Service",
        "visibility_score": 45,
        "critical_issues": [
            "Low review volume for a competitive market despite a perfect 5-star rating.",
            "Suboptimal Google Business Profile categories and incomplete services section.",
            "Lack of consistent Google Posts and engagement with the Q&A section."
        ],
        "estimated_monthly_searches_lost": 120,
        "estimated_monthly_revenue_lost_usd": 3500,
        "top_3_fixes": [
            "Implement a proactive strategy to consistently solicit more customer reviews.",
            "Optimize Google Business Profile categories and populate the services section.",
            "Regularly publish Google Posts with offers and updates."
        ],
        "audit_summary": "Jim Stephens Foreign Car Service has an excellent 5-star rating but needs to significantly increase its review volume and optimize its Google Business Profile to capture more local search traffic. By focusing on these areas, the business can attract more customers and grow its online presence."
    }

    path = generate_audit_report(test_business, test_audit)
    print(f"\nReport generated: {path}")
    print("Open this file in your browser to preview it.")